package com.custodia.supply.item.dto.product;

import com.custodia.supply.validation.UniqueProductCode;

import jakarta.validation.constraints.NotEmpty;

@UniqueProductCode
public class ProductFormDTO {
	private Long id;

	@NotEmpty
	private String code; // "G-P19880-" generated by the provider

	@NotEmpty
	private String name;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
