package com.custodia.supply.item.dto.product;


public class ProductViewDTO {
	
	
	private Long id;


	private String code; // "G-P19880-" generated by the provider
	
	
	private String name;


	public Long getIdLabel() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public String getCodeLabel() {
		return (code == null || code.isBlank()) ? "No asigned" : code;

	}


	public void setCode(String code) {
		this.code = code;
	}


	public String getNameLabel() {
		return (name == null || name.isBlank()) ? "No asigned" : name;

	}


	public void setName(String name) {
		this.name = name;
	}
	
	
}
