spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPLYFLOW_SMTP_USER}           # define como variable de entorno
    password: ${SUPPLYFLOW_SMTP_APP_PASSWORD}   # define como variable de entorno
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} 