spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: supplyflow.firstclass@gmail.com
    password: hmwkvfpzsnabsdqw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
